### PR TITLE
setup upgrade fails

### PR DESCRIPTION
**Pull request by danrcoull**
in magento 2.2 setup upgrade was failing on rename, the updateAttribute code where wrong way round.

### CODE REVIEW

**Comment by Amadeco** [comment]
Thank you for the fix.

**Comment by danrcoull** [comment]
Not a problem

**Comment by Amadeco** [comment]
Good evening,

I have some time to debug the extension. Efectly, the patch @danrcoull pull fix the mysql setup issue, but, the calling entities is not correct anymore (the fact ratings_summary is equal to rating_summary now).

I solve the problem in files:
new/vendor/smile/module-elasticsuite-rating/Model/Layer/FilterList.php
Line 36
rewrite the condition ratings_summary to equal rating_summary

new/vendor/smile/module-elasticsuite-rating/Model/Product/Indexer/Fulltext/Datasource/RatingData.php
rewrite ratings_summary's string to equal rating_summary

new/vendor/smile/module-elasticsuite-rating/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/RatingData.php
rewrite ratings_summary's string to equal rating_summary

Could you take a look ? I do this in a hurry just to display the filter in our products listing in our staging website.

Cheers,
Ilan PARMENTIER

Current version of Magento : Magento 2.2.2

**Comment by Amadeco** [comment]
Also, take in account this patch is not in conflict with issue #2.

**Comment by romainruaud** [comment]
No.

The attribute cannot be named 'rating_summary'. Because it was collisioning with already existing Magento methods like getRatingSummary . See #2 .

I will ensure the rename of the attribute is running properly.

Regards.

**Pull request closed without merging**
